MasterAnnonceLogin {
    fr.uit.univparis8.tpair.tpair1.security.jaas.DbLoginModule required
        debug=false;
};

MasterAnnonceToken {
    fr.uit.univparis8.tpair.tpair1.security.jaas.TokenLoginModule required
        debug=false;
};
